# GitHub Actions for GEOS
#
# Paul Ramsey <pramsey at cleverelephant dot ca>
# Based on AZP configuration by Mateusz Loskot <mateusz at loskot dot net>

name: 'CI'

on:
  push:
    paths-ignore:
      - 'web/**'
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read  #  to fetch code (actions/checkout)

env:
  CCACHE_BASEDIR: ${{ github.workspace }}
  CCACHE_DIR: ${{ github.workspace }}/.ccache
  CCACHE_COMPRESS: "true"
  CCACHE_COMPRESSLEVEL: "6"
  CCACHE_MAXSIZE: "300M"

jobs:

  windows-msvc-ninja:
    name: Windows (MSVC Ninja)
    strategy:
      fail-fast: false
      matrix:
        ci:
        - os: windows-2022
          cxxstd: 20
          arch: x64
        - os: windows-2025
          cxxstd: 20
          arch: x64

    runs-on: ${{ matrix.ci.os }}
    steps:

    - uses: actions/checkout@v6.0.2

    - name: Retrieve build cache
      uses: actions/cache/restore@v5
      id: restore-cache
      with:
        path: .ccache
        key: msvc-ninja-${{ matrix.ci.os }}-${{ matrix.ci.cxxstd }}-${{ matrix.ci.arch }}-${{ github.ref_name }}-${{ github.run_id }}
        restore-keys: msvc-ninja-${{ matrix.ci.os }}-${{ matrix.ci.cxxstd }}-${{ matrix.ci.arch }}

    - name: 'Setup'
      run: choco install ccache ninja

    - name: Activate MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: ${{ matrix.ci.arch }}

    - name: 'Build'
      env:
        CCACHE_DIR: ${{ github.workspace }}\.ccache
      shell: cmd
      run: |
        cmake --version
        cmake ^
          -G Ninja ^
          -D CMAKE_BUILD_TYPE=Release ^
          -D CMAKE_CXX_STANDARD=${{ matrix.ci.cxxstd }} ^
          -D BUILD_SHARED_LIBS=ON ^
          -D USE_CCACHE=ON ^
          -D CMAKE_CXX_FLAGS=/fsanitize=address ^
          -S . -B build
        IF %ERRORLEVEL% NEQ 0 exit /B 1
        cmake --build build --config Release -j 4
        IF %ERRORLEVEL% NEQ 0 exit /B 1
        ccache --show-stats --verbose

    - name: Save build cache
      uses: actions/cache/save@v5
      with:
        path: .ccache
        key: ${{ steps.restore-cache.outputs.cache-primary-key }}

    - name: 'Test'
      working-directory: build
      run: ctest --output-on-failure -C Release
